### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kurtpayne** [arraypad/php-memoize#2]
I'm running this in CentOS 5.7 64-bit and php 5.3.3.  I've installed memoize and the memory storage engine.  I'm getting a segfault.  GDB backtrace included:

<pre>
(gdb) run test.php
Starting program: /usr/bin/php test.php
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x2aaaaaaab000
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00002aaab096b61d in zif_memoize_call (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=0x0, this_ptr=<value optimized out>, 
    return_value_used=<value optimized out>) at /root/php-memoize/memoize.c:317
317         if (call_user_function(&fe->common.scope->function_table, obj_pp, callable, *return_value_ptr, argc, (argc ? *args : NULL) TSRMLS_CC) == FAILURE) {
(gdb) bt
#0  0x00002aaab096b61d in zif_memoize_call (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=0x0, this_ptr=<value optimized out>, 
    return_value_used=<value optimized out>) at /root/php-memoize/memoize.c:317
#1  0x00000000005e7789 in ?? ()
#2  0x00000000005bd84b in execute ()
#3  0x0000000000599df5 in zend_execute_scripts ()
#4  0x000000000054ace8 in php_execute_script ()
#5  0x0000000000622b7e in ?? ()
#6  0x00000039d061d994 in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000421789 in _start ()
</pre>

**Comment by arraypad** [comment]
This is now fixed, thanks for the report :)

**Comment by kurtpayne** [comment]
I have updated and recompiled, but I am still getting this same error (just line 323).

I can provide access to a sandboxed test server, just message me.

**Comment by arraypad** [comment]
Cheers for checking it so quickly.

Github won't let me message you because it apparently doesn't have an email address for you, anyway if you could paste a script I can use to reproduce the error that would be great :)

**Comment by kurtpayne** [comment]
<pre>
(gdb) run memoize_test.php
Starting program: /usr/bin/php memoize_test.php
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffebb4f4b3 in zif_memoize_call (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=0x0, this_ptr=<value optimized out>, return_value_used=1) at /root/php-memoize/memoize.c:323
323                     if (call_user_function(&fe->common.scope->function_table, obj_pp, callable, *return_value_ptr, argc, (argc ? *args : NULL) TSRMLS_CC) == FAILURE) {
(gdb) bt
#0  0x00007fffebb4f4b3 in zif_memoize_call (ht=<value optimized out>, return_value=<value optimized out>, return_value_ptr=0x0, this_ptr=<value optimized out>, return_value_used=1) at /root/php-memoize/memoize.c:323
#1  0x00000000005f5378 in ?? ()
#2  0x00000000005cc6b0 in execute ()
#3  0x00000000005a6ded in zend_execute_scripts ()
#4  0x0000000000555078 in php_execute_script ()
#5  0x0000000000630b25 in ?? ()
#6  0x00007ffff51eccdd in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000421ea9 in _start ()
</pre>

**Comment by arraypad** [comment]
Could you also paste the contents of memoize_test.php please?

**Comment by kurtpayne** [comment]
I'm sorry I overlooked that.

<pre>

function my_expensive_function($x) {
    sleep(10);
    return $x . 'bar';
}

memoize('my_expensive_function');

// now calls to my_expensive_function() are cached by their arguments

echo my_expensive_function('foo'); // returns "foobar" in 10s
echo my_expensive_function('foo'); // returns "foobar" in 0.0001s

</pre>

**Comment by stevenyesz** [comment]
hello, how about this issue now.
I can also reproduce this issue.
